---
title: "03.2 Analysis SEM"
output:
  html_document:
    df_print: paged
---


```{r, include = F}
rm(list = ls())
```


```{r setup, include=FALSE}
library(pacman)
pacman::p_load("tidyverse", 
               "ggpubr", 
               "ragg", 
               "lavaan",
               "fastDummies")

knitr::opts_chunk$set(message = F, warning = F)

```


```{r load dfs}
#df <- readRDS(here::here("data","df.RDS"))
df_na <- readRDS(here::here("data", "df_na.RDS"))
df_macro <- readRDS(here::here("data", "df_macro.RDS"))

```


## Mediation Models

### Set up Data

```{r setupSEM}
# cross-level interaction
df_na <- df_na %>%
  mutate(incdXcpiZ = incdiff_large_w*cpiZ,
         incdXgovZ = incdiff_large_w*noconf_govZ,
         incdXlibZ = incdiff_large_w*libZ,
         incdXlibZXgdp = incdXlibZ*gdp_pc_10k_C,
         incdXgovZXgdp = incdXgovZ*gdp_pc_10k_C,
         incdXcpiZXgdp = incdXcpiZ*gdp_pc_10k_C)

# remove missing for SEM
df_na_libZ <- subset(df_na, !is.na(libZ)) %>%
  dummy_cols(select_columns = 'iso3c_wave')

df_na_govZ <- subset(df_na, !is.na(noconf_govZ)) %>%
  dummy_cols(select_columns = 'iso3c_wave')

df_na_cpiZ <- subset(df_na, !is.na(cpiZ)) %>%
  dummy_cols(select_columns = 'iso3c_wave')

# create matrix to collect chi-sq tests
sem_outs <- as.data.frame(matrix(nrow = 18, ncol = 4))
colnames(sem_outs) <- c("Model", "Fixed_Value", "Standard_P", "Robust_P")

sem_outs[,1] <- c("Liberal_05", "LiberalXGDP_05", "Liberal_07", "LiberalXGDP_07", "Liberal_10", "LiberalXGDP_10",
                  "Lack_trust_05", "Lack_trustXGDP_05", "Lack_trust_07", "Lack_trustXGDP_07", "Lack_trust_10", "Lack_trustXGDP_10",
                  "Corrupt_05", "CorruptXGDP_05", "Corrupt_07", "CorruptXGDP_07", "Corrupt_10", "CorruptXGDP_10")

sem_outs[,2] <- c("-.05", "-.05", "-.07", "-.07", "-.10", "-.10", "-.05", "-.05", "-.07", "-.07", "-.10", "-.10", "-.05", "-.05", "-.07", "-.07", "-.10", "-.10")
```

### Liberal Values

```{r med_libZ, include = T, echo = T}


# the stricter parameters of SEM lead us to take the simplest model of the within-country variance only
# thus we do not need these country dummies, although this is one way to set them up
# first non-NA on libZ country-wave is AUS1992, but one needs to be dropped as ref category so next is 
iso3c_wave <- colnames(df_na_libZ[(match("iso3c_wave_AUS_1999",names(df_na_libZ))):(length(df_na_libZ[1,]))])
intercepts <- paste0(iso3c_wave, collapse=" + ")


# lavaan automatically tests the model with and without the fixed parameter, so there is no need to model it without 
# its an equal fit test with one degree of freedom

# without gdp interaction
m0_lib_05 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ libZ
  gov_redist_C ~ -0.05*incdXlibZ'

m0_lib_07 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ libZ
  gov_redist_C ~ -0.07*incdXlibZ'

m0_lib_10 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ libZ
  gov_redist_C ~ -0.10*incdXlibZ'

# gdp interaction
m1_lib_05 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ libZ
  gov_redist_C ~ -0.05*incdXlibZXgdp'

m1_lib_07 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ libZ
  gov_redist_C ~ -0.07*incdXlibZXgdp'

m1_lib_10 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ libZ
  gov_redist_C ~ -0.10*incdXlibZXgdp'

# as we focus on within variance, we only need do robust clustering for our country-wave variable

m0_lib_fit_05 <- sem(m0_lib_05, data = df_na_libZ, cluster = "iso3c_wave")
m1_lib_fit_05 <- sem(m1_lib_05, data = df_na_libZ, cluster = "iso3c_wave")

m0_lib_fit_07 <- sem(m0_lib_07, data = df_na_libZ, cluster = "iso3c_wave")
m1_lib_fit_07 <- sem(m1_lib_07, data = df_na_libZ, cluster = "iso3c_wave")

m0_lib_fit_10 <- sem(m0_lib_10, data = df_na_libZ, cluster = "iso3c_wave")
m1_lib_fit_10 <- sem(m1_lib_10, data = df_na_libZ, cluster = "iso3c_wave")

sem_outs[1,3] <- m0_lib_fit_05@test[["standard"]][["pvalue"]]
sem_outs[1,4] <- m0_lib_fit_05@test[["yuan.bentler.mplus"]][["pvalue"]]
sem_outs[3,3] <- m0_lib_fit_07@test[["standard"]][["pvalue"]]
sem_outs[3,4] <- m0_lib_fit_07@test[["yuan.bentler.mplus"]][["pvalue"]]
sem_outs[5,3] <- m0_lib_fit_10@test[["standard"]][["pvalue"]]
sem_outs[5,4] <- m0_lib_fit_10@test[["yuan.bentler.mplus"]][["pvalue"]]

sem_outs[2,3] <- m1_lib_fit_05@test[["standard"]][["pvalue"]]
sem_outs[2,4] <- m1_lib_fit_05@test[["yuan.bentler.mplus"]][["pvalue"]]
sem_outs[4,3] <- m1_lib_fit_07@test[["standard"]][["pvalue"]]
sem_outs[4,4] <- m1_lib_fit_07@test[["yuan.bentler.mplus"]][["pvalue"]]
sem_outs[6,3] <- m1_lib_fit_10@test[["standard"]][["pvalue"]]
sem_outs[6,4] <- m1_lib_fit_10@test[["yuan.bentler.mplus"]][["pvalue"]]

```


``` {r med_govZ}
# without gdp interaction
m0_gov_05 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ noconf_govZ
  gov_redist_C ~ -0.05*incdXgovZ'

m0_gov_07 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ noconf_govZ
  gov_redist_C ~ -0.07*incdXgovZ'

m0_gov_10 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ noconf_govZ
  gov_redist_C ~ -0.10*incdXgovZ'

# gdp interaction
m1_gov_05 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ noconf_govZ
  gov_redist_C ~ -0.05*incdXgovZXgdp'

m1_gov_07 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ noconf_govZ
  gov_redist_C ~ -0.07*incdXgovZXgdp'

m1_gov_10 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ noconf_govZ
  gov_redist_C ~ -0.10*incdXgovZXgdp'

# as we focus on within variance, we only need do robust clustering for our country-wave variable

m0_gov_fit_05 <- sem(m0_gov_05, data = df_na_govZ, cluster = "iso3c_wave")
m1_gov_fit_05 <- sem(m1_gov_05, data = df_na_govZ, cluster = "iso3c_wave")

m0_gov_fit_07 <- sem(m0_gov_07, data = df_na_govZ, cluster = "iso3c_wave")
m1_gov_fit_07 <- sem(m1_gov_07, data = df_na_govZ, cluster = "iso3c_wave")

m0_gov_fit_10 <- sem(m0_gov_10, data = df_na_govZ, cluster = "iso3c_wave")
m1_gov_fit_10 <- sem(m1_gov_10, data = df_na_govZ, cluster = "iso3c_wave")


sem_outs[7,3] <- m0_gov_fit_05@test[["standard"]][["pvalue"]]
sem_outs[7,4] <- m0_gov_fit_05@test[["yuan.bentler.mplus"]][["pvalue"]]
sem_outs[9,3] <- m0_gov_fit_07@test[["standard"]][["pvalue"]]
sem_outs[9,4] <- m0_gov_fit_07@test[["yuan.bentler.mplus"]][["pvalue"]]
sem_outs[11,3] <- m0_gov_fit_10@test[["standard"]][["pvalue"]]
sem_outs[11,4] <- m0_gov_fit_10@test[["yuan.bentler.mplus"]][["pvalue"]]

sem_outs[8,3] <- m1_gov_fit_05@test[["standard"]][["pvalue"]]
sem_outs[8,4] <- m1_gov_fit_05@test[["yuan.bentler.mplus"]][["pvalue"]]
sem_outs[10,3] <- m1_gov_fit_07@test[["standard"]][["pvalue"]]
sem_outs[10,4] <- m1_gov_fit_07@test[["yuan.bentler.mplus"]][["pvalue"]]
sem_outs[12,3] <- m1_gov_fit_10@test[["standard"]][["pvalue"]]
sem_outs[12,4] <- m1_gov_fit_10@test[["yuan.bentler.mplus"]][["pvalue"]]

```


### Corruption Perceptions Index

``` {r med_govZ}
# without gdp interaction
m0_cpi_05 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ cpiZ
  gov_redist_C ~ -0.05*incdXcpiZ'

m0_cpi_07 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ cpiZ
  gov_redist_C ~ -0.07*incdXcpiZ'

m0_cpi_10 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ cpiZ
  gov_redist_C ~ -0.10*incdXcpiZ'

# gdp interaction
m1_cpi_05 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ cpiZ
  gov_redist_C ~ -0.05*incdXcpiZXgdp'

m1_cpi_07 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ cpiZ
  gov_redist_C ~ -0.07*incdXcpiZXgdp'

m1_cpi_10 <- '
  gov_redist_C ~ incdiff_large_w
  gov_redist_C ~ cpiZ
  gov_redist_C ~ -0.10*incdXcpiZXgdp'

# as we focus on within variance, we only need do robust clustering for our country-wave variable

m0_cpi_fit_05 <- sem(m0_cpi_05, data = df_na_cpiZ, cluster = "iso3c_wave")
m1_cpi_fit_05 <- sem(m1_cpi_05, data = df_na_cpiZ, cluster = "iso3c_wave")

m0_cpi_fit_07 <- sem(m0_cpi_07, data = df_na_cpiZ, cluster = "iso3c_wave")
m1_cpi_fit_07 <- sem(m1_cpi_07, data = df_na_cpiZ, cluster = "iso3c_wave")

m0_cpi_fit_10 <- sem(m0_cpi_10, data = df_na_cpiZ, cluster = "iso3c_wave")
m1_cpi_fit_10 <- sem(m1_cpi_10, data = df_na_cpiZ, cluster = "iso3c_wave")


sem_outs[13,3] <- m0_cpi_fit_05@test[["standard"]][["pvalue"]]
sem_outs[13,4] <- m0_cpi_fit_05@test[["yuan.bentler.mplus"]][["pvalue"]]
sem_outs[15,3] <- m0_cpi_fit_07@test[["standard"]][["pvalue"]]
sem_outs[15,4] <- m0_cpi_fit_07@test[["yuan.bentler.mplus"]][["pvalue"]]
sem_outs[17,3] <- m0_cpi_fit_10@test[["standard"]][["pvalue"]]
sem_outs[17,4] <- m0_cpi_fit_10@test[["yuan.bentler.mplus"]][["pvalue"]]

sem_outs[14,3] <- m1_cpi_fit_05@test[["standard"]][["pvalue"]]
sem_outs[14,4] <- m1_cpi_fit_05@test[["yuan.bentler.mplus"]][["pvalue"]]
sem_outs[16,3] <- m1_cpi_fit_07@test[["standard"]][["pvalue"]]
sem_outs[16,4] <- m1_cpi_fit_07@test[["yuan.bentler.mplus"]][["pvalue"]]
sem_outs[18,3] <- m1_cpi_fit_10@test[["standard"]][["pvalue"]]
sem_outs[18,4] <- m1_cpi_fit_10@test[["yuan.bentler.mplus"]][["pvalue"]]

sem_outs[,3] <- round(sem_outs[,3], 4)
sem_outs[,4] <- round(sem_outs[,4], 4)

```

### Question Wording

```{r wording}
liberal_redist_label <- "Government should take more responsibility to ensure that everyone is provided for [versus] People should take more responsibility to provide for themselves"
liberal_label <- "Private ownership of business and industry should be increased [versus] government ownership..."
confidence_gov_label <- "I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all? [the government]"
democratic_label <- "And how democratically is this country being governed today? Again using a scale from 1 to 10, where 1 means that it is “not at all democratic” and 10 means that it is “completely democratic,” what position would you choose?"
```

Colophon

```{r colophon}
sessionInfo()
```